@extends('lecturer.app-lecturer-create-materi')
@section('ketjudul', 'Rekap Nilai')
@section('judul', 'Rekap Siswa')
@section('content')
<div class="mb-6"><a href="{{ route('lecturer.akademik.nilai.students', $pengajaranDosen) }}" class="text-sm text-teal hover:underline">← Kembali ke daftar siswa</a><h1 class="mt-2 font-display text-xl font-semibold">{{ $student->user->name ?? '-' }}</h1><p class="mt-1 text-sm text-ink/50">{{ $student->nim }} · {{ $pengajaranDosen->kelas->matakuliah->nama_mk }} · Kelas {{ $pengajaranDosen->kelas->kode_kelas }}</p></div>
<div class="mb-7 grid gap-4 sm:grid-cols-3"><div class="rounded-2xl border border-line bg-white p-5"><p class="text-xs uppercase text-ink/45">Rata-rata Tugas</p><p class="mt-2 text-3xl font-semibold">{{ $detail['tugas_avg'] !== null ? number_format($detail['tugas_avg'],2) : '-' }}</p></div><div class="rounded-2xl border border-line bg-white p-5"><p class="text-xs uppercase text-ink/45">Rata-rata Quiz</p><p class="mt-2 text-3xl font-semibold">{{ $detail['quiz_avg'] !== null ? number_format($detail['quiz_avg'],2) : '-' }}</p></div><div class="rounded-2xl border border-line bg-white p-5"><p class="text-xs uppercase text-ink/45">Kehadiran</p><p class="mt-2 text-3xl font-semibold">{{ $detail['attendance_percent'] !== null ? number_format($detail['attendance_percent'],2).'%' : '-' }}</p><p class="mt-1 text-xs text-ink/45">H {{ $detail['hadir'] }} · I {{ $detail['izin'] }} · S {{ $detail['sakit'] }} · A {{ $detail['alpha'] }}</p></div></div>
<div class="space-y-7">
<section class="overflow-hidden rounded-2xl border border-line bg-white"><div class="border-b border-line p-5"><h2 class="font-display text-lg font-semibold">Rekap Tugas</h2></div><div class="divide-y divide-line">@forelse($detail['tugas'] as $tugas)@php($j=$detail['tugasJawaban']->get($tugas->id))<div class="flex items-center justify-between gap-4 p-5"><div><p class="font-medium">{{ $tugas->judul }}</p><p class="mt-1 text-xs text-ink/45">{{ $j?->status ? str_replace('_',' ',ucwords($j->status,'_')) : 'Belum submit' }}</p></div><span class="font-semibold">{{ $j?->skor !== null ? number_format((float)$j->skor,2) : '-' }}</span></div>@empty<div class="p-6 text-sm text-ink/50">Belum ada tugas.</div>@endforelse</div></section>
<section class="overflow-hidden rounded-2xl border border-line bg-white"><div class="border-b border-line p-5"><h2 class="font-display text-lg font-semibold">Rekap Quiz</h2></div><div class="divide-y divide-line">@forelse($detail['quizzes'] as $quiz)@php($j=$detail['quizJawaban']->get($quiz->id))<div class="flex items-center justify-between gap-4 p-5"><div><p class="font-medium">{{ $quiz->judul }}</p><p class="mt-1 text-xs text-ink/45">{{ $j ? 'Sudah dikerjakan' : 'Belum dikerjakan' }}</p></div>@if($j)<a href="{{ route('lecturer.akademik.quiz.jawaban.show', [$quiz,$j]) }}" class="font-semibold text-teal">{{ number_format((float)$j->skor,2) }} →</a>@else<span>-</span>@endif</div>@empty<div class="p-6 text-sm text-ink/50">Belum ada quiz.</div>@endforelse</div></section>
<section class="overflow-x-auto rounded-2xl border border-line bg-white"><div class="border-b border-line p-5"><h2 class="font-display text-lg font-semibold">Rekap Absensi</h2></div><table class="min-w-full text-sm"><thead class="bg-paper text-left text-xs uppercase text-ink/50"><tr><th class="px-5 py-3">Pertemuan</th><th class="px-5 py-3">Judul</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Waktu</th></tr></thead><tbody class="divide-y divide-line">@forelse($detail['sesi'] as $sesi)@php($a=$detail['absensi']->get($sesi->id))<tr><td class="px-5 py-4">{{ $sesi->pertemuan_ke }}</td><td class="px-5 py-4">{{ $sesi->judul ?? '-' }}</td><td class="px-5 py-4 font-semibold">{{ strtoupper($a?->status ?? 'alpha') }}</td><td class="px-5 py-4 text-ink/50">{{ $a?->waktu_absen?->format('d M Y H:i') ?? '-' }}</td></tr>@empty<tr><td colspan="4" class="px-5 py-6 text-center text-ink/50">Belum ada sesi absensi.</td></tr>@endforelse</tbody></table></section>
</div>
@endsection
